// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type User struct {
	ID                 int32
	FirstName          string
	LastName           string
	Email              string
	IsAdmin            bool
	StarsCount         int32
	IsOpenToReview     sql.NullBool
	ContributionsCount int32
	ReviewCount        int32
	ContentCount       int32
}
